blank_issues_enabled: true
contact_links:
  - name: Report Bug ğŸ› Or Feature Request ğŸ’ 
    url: https://discord.gg/ZTfpT4ejRt
    about: Please do Feature Requests and Bug reports on our discord.
  - name: Our Discord
    url: https://discord.com/invite/QjwdY3d
    about: Please ask your questions and report bugs here.
  - name: The Wiki
    url: https://github.com/jojodmo/CustomItems/wiki
    about: Please Take a look at the wiki.
